# Generated by Django 5.0.6 on 2024-12-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Родитель', 'verbose_name_plural': 'Родители'},
        ),
        migrations.AlterModelOptions(
            name='schoolkid',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='schoolkid',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='schoolkid',
            name='entry_year',
            field=models.IntegerField(null=True, verbose_name='Год начала обучения'),
        ),
        migrations.AlterField(
            model_name='schoolkid',
            name='group_letter',
            field=models.CharField(blank=True, max_length=1, verbose_name='Литера класса'),
        ),
        migrations.AlterField(
            model_name='schoolkid',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='bot.parent', verbose_name='Родители'),
        ),
        migrations.AlterField(
            model_name='schoolkid',
            name='year_of_study',
            field=models.IntegerField(null=True, verbose_name='Год обучения'),
        ),
    ]
