# Generated by Django 5.0.6 on 2024-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolkid',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram ID'),
        ),
    ]
