# Generated by Django 5.0.6 on 2024-12-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_schoolkid_telegram_id_teacher_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('telegram_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram ID')),
            ],
        ),
        migrations.AddField(
            model_name='schoolkid',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='bot.parent', verbose_name='родители'),
        ),
    ]
