# Generated by Django 5.0.6 on 2024-12-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='schoolkid',
        ),
        migrations.AddField(
            model_name='homework',
            name='group_letter',
            field=models.CharField(blank=True, help_text='Буква класса, которому назначено задание', max_length=1, verbose_name='Литера класса'),
        ),
        migrations.AddField(
            model_name='homework',
            name='schoolkids',
            field=models.ManyToManyField(blank=True, help_text='Ученики, если задание задается не всему классу', related_name='homeworks', to='bot.schoolkid', verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='homework',
            name='year_of_study',
            field=models.IntegerField(blank=True, help_text='Год обучения класса, которому назначено задание', null=True, verbose_name='Год обучения'),
        ),
    ]
