# Generated by Django 5.0.6 on 2024-12-14 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_homework_schoolkid_homework_group_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='year_of_study',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='year_of_study',
        ),
        migrations.RemoveField(
            model_name='schoolkid',
            name='year_of_study',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year_of_study',
        ),
        migrations.AlterField(
            model_name='chastisement',
            name='created',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='chastisement',
            name='schoolkid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.schoolkid', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='chastisement',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='chastisement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='chastisement',
            name='text',
            field=models.TextField(verbose_name='Замечание'),
        ),
        migrations.AlterField(
            model_name='commendation',
            name='created',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='commendation',
            name='schoolkid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.schoolkid', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='commendation',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='commendation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='commendation',
            name='text',
            field=models.TextField(verbose_name='Похвала'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='group_letter',
            field=models.CharField(blank=True, help_text='Класс, которому назначено задание', max_length=1, verbose_name='Литера класса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group_letter',
            field=models.CharField(db_index=True, max_length=1, verbose_name='Литера класса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.CharField(db_index=True, help_text='Класс где проходят занятия.', max_length=50, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='timeslot',
            field=models.IntegerField(db_index=True, help_text='Номер слота в расписании уроков на этот день.', verbose_name='Слот'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='created',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='points',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='schoolkid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.schoolkid', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='teacher_note',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождения'),
        ),
    ]
