# Generated by Django 5.0.6 on 2024-12-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_homework_year_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolkid',
            name='group_letter',
        ),
        migrations.AddField(
            model_name='schoolkid',
            name='class_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Класс'),
        ),
    ]
