# Generated by Django 5.0.6 on 2024-12-15 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_schoolkid_group_letter_schoolkid_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год обучения')),
                ('letter', models.CharField(max_length=1, verbose_name='Литера')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.teacher', verbose_name='Классный руководитель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'unique_together': {('year', 'letter')},
            },
        ),
        migrations.AddField(
            model_name='schoolkid',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bot.classgroup', verbose_name='Класс'),
        ),
    ]
