# Generated by Django 5.0.6 on 2024-12-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_classgroup_schoolkid_class_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='group_letter',
        ),
        migrations.AddField(
            model_name='homework',
            name='class_group',
            field=models.ForeignKey(blank=True, help_text='Класс, которому назначено задание', null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.classgroup', verbose_name='Класс'),
        ),
    ]
