# Generated by Django 5.0.6 on 2024-12-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_lesson_options_remove_lesson_group_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='datetime',
            field=models.DateTimeField(db_index=True, help_text='Дата и время начала урока.', null=True, verbose_name='Дата и время'),
        ),
    ]
