# Generated by Django 5.0.6 on 2024-12-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='timeslot',
        ),
        migrations.RemoveField(
            model_name='schoolkid',
            name='entry_year',
        ),
    ]
