# Generated by Django 5.0.6 on 2024-12-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_lesson_datetime_remove_lesson_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subjects',
            field=models.ManyToManyField(help_text='Предметы, которые будут изучаться на этом уроке.', related_name='lessons', to='bot.subject', verbose_name='Предметы'),
        ),
    ]
