# Generated by Django 5.0.6 on 2024-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_lesson_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='schoolkids',
            field=models.ManyToManyField(blank=True, help_text='Ученики, которым назначен этот урок.', related_name='lessons', to='bot.schoolkid', verbose_name='Ученики'),
        ),
    ]
