# Generated by Django 5.0.6 on 2024-12-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_lesson_schoolkids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='room',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='schoolkids',
        ),
    ]
