# Generated by Django 5.0.6 on 2024-12-15 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_remove_lesson_room_remove_lesson_schoolkids'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSubjectOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_orders', to='bot.lesson', verbose_name='Урок')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Порядок предметов в уроке',
                'verbose_name_plural': 'Порядки предметов в уроке',
                'ordering': ['lesson', 'order'],
            },
        ),
    ]
