# Generated by Django 5.0.6 on 2024-12-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_lessonsubjectorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subjects',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default=1, help_text='Предмет, который будет изучаться на этом уроке.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='bot.subject', verbose_name='Предмет'),
        ),
    ]
