# Generated by Django 5.0.6 on 2024-12-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_remove_lesson_subjects_lesson_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subjects',
            field=models.ManyToManyField(help_text='Предметы, которые будут изучаться на этом уроке.', related_name='lessons', to='bot.subject', verbose_name='Предметы'),
        ),
        migrations.DeleteModel(
            name='LessonSubjectOrder',
        ),
    ]
